### ISSUE TITLE
Clicking the Link Encoder Button Sometimes Results in a White Screen

### ISSUE THREAD

**Issue by jcmoore2** [grainger-illinois/CTCast#13]

**Comment by angrave** [comment]
It goes white only the first time the LinkEncoder or the Zoom buttons are clicked.Using the menu you can i) Open the Dev console and see error and trace the stack trace back to "value={postData.ip}" i.e. postData is null when rendering this first TextField component. Why? Is this a react version issue.
ii) If you use the menu to reload the page the error vanishes and the page displays ( because the Useeffect or the onChange source code runs and creates a postData?)

<form autoComplete="off" noValidate className={`${classes.root} ${classes.form}`} onSubmit={handleSubmit}>
                <TextField
                    name="ip"
                    variant="outlined"
                    label="IP Address"
                    fullWidth
                    value={postData.ip}
                    onChange={(e) => setPostData({ ...postData, ip: e.target.value })}

                />

**Comment by angrave** [comment]
The symptoms were fixed in commit 785bef714dc606fb466ca13da9373573589f61fe ; but was the fix really best practice? I havent seen this kind of checking in other react.js apps.
