### ISSUE TITLE
Transcripts and Captions need fixing

### ISSUE THREAD

**Issue by shubhamk008** [grainger-illinois/CTCast#50]
While testing on the beta player with audio descriptions
If we begin sending text through port 2 it is announced (good)
it also shows up as captions very quick
If we begin sending text through port 1, text appears in transcripts (good) but does not show up as captions (worse)
Port 1 text needs to show up as captions as well
Since it does not show up currently but port 2 does very quickly the time it appears, probably needs to be extended
Since port 2 messages are announced, it doesn’t have to show up as captions, they could rather appear in italics, parenthesis, or with an AD before it is designated as Audio
It would be nice if descriptions appeared as captions and transcripts (perhaps later this could be a toggleable button for AD like we have for CC)

**Comment by angrave** [comment]
A lot of this sounds like expected behavior.  The frontend player assumes the first English caption track is for captions. When a second track is found it is assumed that it is the audio descriptions.

The only part that sounds like a bug is the port 1 captions not showing up as captions; which is likely incorrect control codes.

Adding features to the frontend react player is a lower priority than finishing CT-Cast app. Features should be put in the liveplayer github

**Comment by romerorisa** [comment]
Fixed with #61
